# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            BIS180L
tagline:          'Genome Biology Lab'
description:      'A Lab Course at UC Davis to introduce Genetics and Genomics majors to Bioinformatics'
# url:              http://jnmaloof.github.io/BIS180L_web/
baseurl:          /BIS180L_web

author:
  name:           'Julin Maloof'
  url:            http://biosci3.ucdavis.edu/Faculty/Profile/View/241

paginate:         5

# Custom vars
version:          0.1.0

#github:
#  repo:           https://github.com/jnmaloof/BIS180L_web
